FROM node:16.16-alpine as build

WORKDIR /client

COPY . .

RUN npm install --force

# EXPOSE 3001

RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /client/build /usr/share/nginx/html
# new
COPY ./nginx.service.conf.prod /etc/nginx/conf.d/default.conf
EXPOSE 3001
CMD ["nginx", "-g", "daemon off;"]