version: "3.9"

services:
  frontend:
    depends_on:
      - backend
    container_name: survey-app-frontend
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "3001:3001"

  backend:
    container_name: survey-app-backend
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
