FROM node:16.16-alpine

WORKDIR /server
COPY package.json .

COPY . .
COPY .env .env.local
COPY serviceAccountKey.json serviceAccountKey.json
# COPY ./server/.env.production .env.production

EXPOSE 8080

CMD ["npm", "start"]